RustboroCity_Flat1_1F_MapScripts::
	.byte 0

RustboroCity_Flat1_1F_EventScript_Man::
	msgbox RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility, MSGBOX_NPC
	end

RustboroCity_Flat1_1F_EventScript_Woman::
	msgbox RustboroCity_Flat1_1F_Text_PokemonStrange, MSGBOX_NPC
	end

RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility:
	.string "Elkne Pokémon kunt ntwa 'speshioals',\n"
	.string "m'n moedre zeita wok van ik.$"

RustboroCity_Flat1_1F_Text_PokemonStrange:
	.string "Die keirl, dadis inderdoad ne specioaln.$"

