RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "Onze skole vo Temmers is machtig.\p"
	.string "Roxanne is daar als klein meiske begonnen,\n"
	.string "en geeft er nu zelve lesse, das toch skwonne, nie?$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Wudr zin de Roxanne fanclub.\n"
	.string "Lik Swifties ma ton. Roxfannekes.\p"
	.string "Ey, 't is een hobby lik een ander!$"

