gText_Birch_Welcome::
	.string "Elk zinne g'ndag!\n"
	.string "Ik ben Gerrit Callewaert!\p"
	.string "Welkom in Oarelbeke!\n"
	.string "Allez 't is te zeggen,\p"
	.string "dat is een deelgemeente, in Oen!\n"
	.string "Met een Haa. Hoenn e feitelijk!\p"
	.string "Ma we klap'n ier van “OEN.”\n"
	.string "Ik ben teves den “POKéMON Professor”!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Kieknekedaarsie, daar is 't em sè!”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Daddis MARCEL. Zeg ne ke goeiendag!\p"
	.string "MARCEL: Ne goeiendag!\p"
	.string "'Et krioelt 'ier in Oen van\n"
	.string "de POKéMON.\p"
	.string "We zien ze geirn whe,\n"
	.string "ma ajet mij vraagt\l"
	.string "ze zijn der in eerste instantie\l"
	.string "vo mee te batt'rn\p"
	.string "Mo ge moe vooral nie na mie kiek'n\n"
	.string "ik zitte vooral te chillen...\l"
	.string "euh ik bedoel téléwerken in mijn lab.\p"
	.string "Gij ziet er mij lik 't avontuurlijk\n"
	.string "type uit. Awel hè't chance!\p"
	.string "Er zin stiefveel mysteries achter\n"
	.string "al die mahtihe beestjes...\p"
	.string "Kebkik 'n twien nodig da min veldwerk doet,\n"
	.string "en da gaje gij doen eh slimmen.\p"
	.string "of 'ad je gepeisd daje ier in Oen\p"
	.string "een bitje kwam doppen?\n"
	.string "En bebie ma werken zekers...\l"
	.string "Vergeet min pensioen niet!\p" 
	.string "$"

gText_Birch_AndYouAre::
	.string "Ma goed! En nu gawe 't over u 'ebben!\p"
	.string "\n"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "En zijde gij een mannenminsch\n"
	.string "Of een vrominsch?$"

gText_Birch_Difficulty::
	.string "Moh…\p"
	.string "En peisdje dat dit avontuur\n"
	.string "hemakkelik ga zin, of moeilik?$"

gText_Birch_LockDifficulty::
	.string "Moest je 't u bespijten\n"
	.string "kunje 't nog alsan loatr aanpass'n\l"
	.string "lik daje wilt eh.\p"
	.string "Of ge kun et vastzett'n.\n"
	.string "Wilje da vaszetten?\l"
	.string "Ge mot ton nie trunten e seffest\p"
	.string "Kgoat je ma jin ke vroagn.$"

gText_Birch_ChallengeEasy::
	.string "Baja gij!\p"
    .string "Ge goat zwemmen in 't IeksPee\n"
    .string "Tis al ip 't hemak.\p"
    .string "Ge kun 't gelik wanneer daje wilt\n"
    .string "de moeilikid nog aanpassen eh\l"
	.string "En oe noem je gij eigenlijk?$"

gText_Birch_ChallengeNormal::
	.string "A' de crèmekarre passeert...\p"
    .string "paktje gie zekers alsan vanille?\n"
    .string "Daddis 't zowa in 't kort.\p"
    .string "Ge kun 't gelik wanneer daje wilt\n"
    .string "de moeilikid nog aanpassen eh\l"
	.string "En oe noem je gij eigenlijk?$"

gText_Birch_ChallengeHard::
    .string "'t Zal wel zin!\p"
    .string "Iekspee hroei ier nie aan de bwom'n\n"
    .string "Aje battert, 4 items max, 't is al!\p"
	.string "Ge kun 't gelik wanneer daje wilt\n"
    .string "de moeilikid nog aanpassen eh\l"
	.string "En oe noem je gij eigenlijk?$"

gText_Birch_WhatsYourName::
	.string "Moh. Allez dan.\n"
	.string "En oe noem je gij eigenlijk?$"

gText_Birch_SoItsPlayer::
	.string "Ak et goe voor'eb is 't {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah ma hotvert, 't is just!\p"
	.string "Gij zijt gij mijnen nieuwen buur!\p"
	.string "Past ip daje niet te veel lawaai maakt\n"
	.string "na 10 uur, ik weet u wonen é!\l"
	.string "'k Doe u een proces aan!\p"
	.string "......................\p"
	.string "'N is ma een graptje éh Pol!\n"
	.string "euh...{PLAYER}{KUN}.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "How, zieje der gereed voor 'n?\p"
	.string "Jen avontuur behint!\n"
	.string "Courage! En passeert ton ne ke bij et LAB!\p"
	.string "voor een pientje!\p"
	.string "$"
