Text_PictureBookShelf:
	.string "E collectie kleurboek'n.\p"
	.string "Kzoe mie hamuseerd èn,\n"
	.string "moest ik lik 4 zin.$"

Text_BookShelf:
	.string "Tzit stukvol boekn.$"

Text_PokemonCenterBookShelf:
	.string "Pokémon boekskes!\n"
	.string "Amai…\p"
	.string "Precies drama in den Elite 4…\n"
	.string "Tis bikan interessant…bikanst.$"

Text_Vase:
	.string "Die voas ziet er tier ut…\n"
	.string "Ne ké binnenkiekn é…\p"
	.string "Tzit gin zak in.$"

Text_EmptyTrashCan:
	.string "Wuk zit erin?\p"
	.string "Nietn.$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "Pokémon merchandise.$"

Text_Blueprint:
	.string "E vré complex tekeningske.\n"
	.string "'t Es beeeeeire inhewikkeld!\p"
	.string "Ge verstoat er gin klôotn van.$"
