	.align 2
gText_ConfirmSave::
	.string "Wildje ipsloan?$"

gText_AlreadySavedFile::
	.string "Er is al een ipslagbestand.\n"
	.string "Wildjet overskrivn?$"

gText_SavingDontTurnOff::
	.string "Ipsloan…\n"
	.string "Je spel nie utzetn of anders…$"

gText_PlayerSavedGame::
	.string "{PLAYER} ét et spel iphesloan.$"

gText_DifferentSaveFile::
	.string "WOARSKUWINGE!\p"
	.string "Er is al een ipslagbestand.\n"
	.string "Wildjet overskrivn?$"

gText_SaveError::
	.string "Ipslag error.\p"
	.string "Verandert den\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "Ipsloan…\n"
	.string "Je spel nie utzetn of anders…$"
