PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Norman is onzen Gym Leider.\n"
	.string "N'en beir van ne vint.\p"
	.string "Ma ie is nie van alier,\n"
	.string "ie komt van beeeeeere ver.\p"
	.string "Lendééludéé?$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Kèn oois tehen de Norman\n"
	.string "gebatterd. Kzweirem.\p"
	.string "Oe moek et zeggen?\p"
	.string "Nog nwoois zo 'arte ip m'en\n"
	.string "mulle gekregen.$"

