OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Jin twji drie,\n"
	.string "je linkse Pokémon komt eerst ut...\p"
	.string "Aje der mjir ip zak èt,\n"
	.string "kundje de volhorde zelve kiezen\l"
	.string "van je Pokémon.\p"
	.string "{PLAYER}: Ik krih et van jen debiele tips.$"

