SlateportCity_House_MapScripts::
	.byte 0

SlateportCity_House_EventScript_PokefanM::
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
	end

SlateportCity_House_EventScript_Girl::
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
	end

SlateportCity_House_Text_NatureToDoWithStatGains:
	.string "Momo, min vrouwe kun e bitje overdrivvn.\p"
	.string "'k A beter me n'en octopus getrouwd!\n"
	.string "Z'ad dezelfste hedacht toen da ze\p"
	.string "ier die Batter Tente 'add'n hebouwd.\p"
	.string "Moe wel toeheevn,\n"
	.string "ka liev'r e frietkot gezien.$"

SlateportCity_House_Text_MustBeGoingToBattleTent:
	.string "Nieuwpoort es redelik rustih\p"
	.string "vo lik, 75% van 't joar.\n"
	.string "Ton eje die toeristen é.\p"
	.string "Kzeijt nog davers, wuk goat er\n"
	.string "hebeur'n als die ferry massa's\p" 
	.string "meschn nar ier bringt?\p"
	.string "Min rust en kalmte, WEG É!!!$"


