PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Ip reis goan, machtig é..\p"
	.string "Lang heleden, ik gingkik ip zee\n"
	.string "en beklomme de wôgste bergen!\p"
	.string "Nu? Te od en te stif.$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Jaja…\p"
	.string "'t is al gin oar snie'en...\n"
	.string "'t is die krullekes lehhen…!\p"
	.string "Ik zoe zo geirn, de weireld zien…\n"
	.string "Hihantiese bergen beklimn…\p"
	.string "De woeste zji temmn…\n"
	.string "En krupn, in de donkerste hrotn…\p"
	.string "Miskien zelve, een bitje\n"
	.string "heimwee krign…\p"
	.string "Maja! Sinds Dutroux magk nie butn!$"

