SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Een hrwôt skip moakn\n"
	.string "is mjir lik e hrwôt hebouw ip\l"
	.string "pootn zett'n dan e vervoersmidd'l.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Ik wil kanongs ip onzn'en nieuwen boot.\p"
	.string "Ben mo oant greitn whé.\p"
	.string "Tenzij?\p"
	.string "Haha, ninnin. Mo miskien?$"

