DewfordTown_Gym_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, DewfordTown_Gym_OnTransition
	.byte 0

DewfordTown_Gym_OnTransition:
	call DewfordTown_Gym_EventScript_SetFlashLevel
	end

DewfordTown_Gym_EventScript_SetFlashLevel::
	goto_if_defeated TRAINER_BRAWLY_1, DewfordTown_Gym_EventScript_SetLightsOn
	call DewfordTown_Gym_EventScript_CountTrainersDefeated
	copyvar VAR_0x8001, VAR_0x8000
	goto_if_eq VAR_0x8000, 0, DewfordTown_Gym_EventScript_SetFlashLevel7
	goto_if_eq VAR_0x8000, 1, DewfordTown_Gym_EventScript_SetFlashLevel6
	goto_if_eq VAR_0x8000, 2, DewfordTown_Gym_EventScript_SetFlashLevel5
	goto_if_eq VAR_0x8000, 3, DewfordTown_Gym_EventScript_SetFlashLevel4
	goto_if_eq VAR_0x8000, 4, DewfordTown_Gym_EventScript_SetFlashLevel3
	goto_if_eq VAR_0x8000, 5, DewfordTown_Gym_EventScript_SetFlashLevel2
	goto DewfordTown_Gym_EventScript_SetFlashLevel1

DewfordTown_Gym_EventScript_SetLightsOn::
	setflashlevel 0
	return

@ Brightest
DewfordTown_Gym_EventScript_SetFlashLevel1::
	setflashlevel 1
	return

DewfordTown_Gym_EventScript_SetFlashLevel2::
	setflashlevel 2
	return

DewfordTown_Gym_EventScript_SetFlashLevel3::
	setflashlevel 3
	return

DewfordTown_Gym_EventScript_SetFlashLevel4::
	setflashlevel 4
	return

DewfordTown_Gym_EventScript_SetFlashLevel5::
	setflashlevel 5
	return

DewfordTown_Gym_EventScript_SetFlashLevel6::
	setflashlevel 6
	return

@ Darkest
DewfordTown_Gym_EventScript_SetFlashLevel7::
	setflashlevel 7
	return

DewfordTown_Gym_EventScript_BrightenRoom::
	call DewfordTown_Gym_EventScript_CountTrainersDefeated
	nop1
	goto_if_eq VAR_0x8000, VAR_0x8001, DewfordTown_Gym_EventScript_NoLightChange
	copyvar VAR_0x8001, VAR_0x8000
	goto_if_eq VAR_0x8000, 1, DewfordTown_Gym_EventScript_AnimateFlash1Trainer
	goto_if_eq VAR_0x8000, 2, DewfordTown_Gym_EventScript_AnimateFlash2Trainers
	goto_if_eq VAR_0x8000, 3, DewfordTown_Gym_EventScript_AnimateFlash3Trainers
	goto_if_eq VAR_0x8000, 4, DewfordTown_Gym_EventScript_AnimateFlash4Trainers
	goto_if_eq VAR_0x8000, 5, DewfordTown_Gym_EventScript_AnimateFlash5Trainers
	goto_if_eq VAR_0x8000, 6, DewfordTown_Gym_EventScript_AnimateFlash6Trainers

DewfordTown_Gym_EventScript_NoLightChange::
	return

@ NOTE: A little confusingly, a larger animateflash param value is a smaller flash radius
DewfordTown_Gym_EventScript_AnimateFlash1Trainer::
	playse SE_SWITCH
	animateflash 6
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlash2Trainers::
	playse SE_SWITCH
	animateflash 5
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlash3Trainers::
	playse SE_SWITCH
	animateflash 4
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlash4Trainers::
	playse SE_SWITCH
	animateflash 3
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlash5Trainers::
	playse SE_SWITCH
	animateflash 2
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlash6Trainers::
	playse SE_SWITCH
	animateflash 1
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_AnimateFlashFullBrightness::
	playse SE_SWITCH
	animateflash 0
	call DewfordTown_Gym_EventScript_SetFlashLevel
	return

DewfordTown_Gym_EventScript_CountTrainersDefeated::
	setvar VAR_0x8000, 0
	goto_if_not_defeated TRAINER_TAKAO, DewfordTown_Gym_EventScript_CheckJocelyn
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckJocelyn::
	goto_if_not_defeated TRAINER_JOCELYN, DewfordTown_Gym_EventScript_CheckLaura
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckLaura::
	goto_if_not_defeated TRAINER_LAURA, DewfordTown_Gym_EventScript_CheckBrenden
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckBrenden::
	goto_if_not_defeated TRAINER_BRENDEN, DewfordTown_Gym_EventScript_CheckCristian
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckCristian::
	goto_if_not_defeated TRAINER_CRISTIAN, DewfordTown_Gym_EventScript_CheckLilith
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_CheckLilith::
	goto_if_not_defeated TRAINER_LILITH, DewfordTown_Gym_EventScript_StopCountingTrainers
	addvar VAR_0x8000, 1
DewfordTown_Gym_EventScript_StopCountingTrainers::
	return

DewfordTown_Gym_EventScript_Brawly::
	trainerbattle_single TRAINER_BRAWLY_1, DewfordTown_Gym_Text_BrawlyIntro, DewfordTown_Gym_Text_BrawlyDefeat, DewfordTown_Gym_EventScript_BrawlyDefeated, NO_MUSIC
	specialvar VAR_RESULT, ShouldTryRematchBattle
	goto_if_eq VAR_RESULT, TRUE, DewfordTown_Gym_EventScript_BrawlyRematch
	goto_if_unset FLAG_RECEIVED_TM_BULK_UP, DewfordTown_Gym_EventScript_GiveBulkUp2
	msgbox DewfordTown_Gym_Text_BrawlyPostBattle, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_BrawlyDefeated::
	call DewfordTown_Gym_EventScript_AnimateFlashFullBrightness
	message DewfordTown_Gym_Text_ReceivedKnuckleBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis, MSGBOX_DEFAULT
	setflag FLAG_DEFEATED_DEWFORD_GYM
	setflag FLAG_BADGE02_GET
	addvar VAR_PETALBURG_GYM_STATE, 1
	call_if_eq VAR_PETALBURG_GYM_STATE, 6, Common_EventScript_ReadyPetalburgGymForBattle
	setvar VAR_0x8008, 2
	call Common_EventScript_SetGymTrainers
	call DewfordTown_Gym_EventScript_GiveBulkUp
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox DewfordTown_Gym_Text_RegisteredBrawly, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_BRAWLY_MATCH_CALL
	setvar VAR_ROXANNE_CALL_STEP_COUNTER, 0
	setflag FLAG_ENABLE_ROXANNE_FIRST_CALL
	release
	end

DewfordTown_Gym_EventScript_GiveBulkUp::
	giveitem ITEM_TM_BULK_UP
	goto_if_eq VAR_RESULT, 0, Common_EventScript_BagIsFull
	msgbox DewfordTown_Gym_Text_ExplainBulkUp, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM_BULK_UP
	return

DewfordTown_Gym_EventScript_GiveBulkUp2:
	giveitem ITEM_TM_BULK_UP
	goto_if_eq VAR_RESULT, 0, Common_EventScript_ShowBagIsFull
	msgbox DewfordTown_Gym_Text_ExplainBulkUp, MSGBOX_DEFAULT
	setflag FLAG_RECEIVED_TM_BULK_UP
	release
	end

DewfordTown_Gym_EventScript_BrawlyRematch::
	trainerbattle_rematch_double TRAINER_BRAWLY_1, DewfordTown_Gym_Text_BrawlyPreRematch, DewfordTown_Gym_Text_BrawlyRematchDefeat, DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons
	msgbox DewfordTown_Gym_Text_BrawlyPostRematch, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_Takao::
	trainerbattle_single TRAINER_TAKAO, DewfordTown_Gym_Text_TakaoIntro, DewfordTown_Gym_Text_TakaoDefeat, DewfordTown_Gym_EventScript_TakaoBrightenRoom
	msgbox DewfordTown_Gym_Text_TakaoPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_TakaoBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Jocelyn::
	trainerbattle_single TRAINER_JOCELYN, DewfordTown_Gym_Text_JocelynIntro, DewfordTown_Gym_Text_JocelynDefeat, DewfordTown_Gym_EventScript_JocelynBrightenRoom
	msgbox DewfordTown_Gym_Text_JocelynPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_JocelynBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Laura::
	trainerbattle_single TRAINER_LAURA, DewfordTown_Gym_Text_LauraIntro, DewfordTown_Gym_Text_LauraDefeat, DewfordTown_Gym_EventScript_LauraBrightenRoom
	msgbox DewfordTown_Gym_Text_LauraPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_LauraBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Brenden::
	trainerbattle_single TRAINER_BRENDEN, DewfordTown_Gym_Text_BrendenIntro, DewfordTown_Gym_Text_BrendenDefeat, DewfordTown_Gym_EventScript_BrendenBrightenRoom
	msgbox DewfordTown_Gym_Text_BrendenPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_BrendenBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Cristian::
	trainerbattle_single TRAINER_CRISTIAN, DewfordTown_Gym_Text_CristianIntro, DewfordTown_Gym_Text_CristianDefeat, DewfordTown_Gym_EventScript_CristianBrightenRoom
	msgbox DewfordTown_Gym_Text_CristianPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_CristianBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_Lilith::
	trainerbattle_single TRAINER_LILITH, DewfordTown_Gym_Text_LilithIntro, DewfordTown_Gym_Text_LilithDefeat, DewfordTown_Gym_EventScript_LilithBrightenRoom
	msgbox DewfordTown_Gym_Text_LilithPostBattle, MSGBOX_AUTOCLOSE
	end

DewfordTown_Gym_EventScript_LilithBrightenRoom::
	call DewfordTown_Gym_EventScript_BrightenRoom
	release
	end

DewfordTown_Gym_EventScript_GymGuide::
	lock
	faceplayer
	goto_if_set FLAG_DEFEATED_DEWFORD_GYM, DewfordTown_Gym_EventScript_GymGuidePostVictory
	msgbox DewfordTown_Gym_Text_GymGuideAdvice, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_GymGuidePostVictory::
	msgbox DewfordTown_Gym_Text_GymGuidePostVictory, MSGBOX_DEFAULT
	release
	end

DewfordTown_Gym_EventScript_LeftGymStatue::
	lockall
	goto_if_set FLAG_BADGE02_GET, DewfordTown_Gym_EventScript_GymStatueCertified
	goto DewfordTown_Gym_EventScript_GymStatue
	end

DewfordTown_Gym_EventScript_RightGymStatue::
	lockall
	goto_if_set FLAG_BADGE02_GET, DewfordTown_Gym_EventScript_GymStatueCertified
	goto DewfordTown_Gym_EventScript_GymStatue
	end

DewfordTown_Gym_EventScript_GymStatueCertified::
	msgbox DewfordTown_Gym_Text_GymStatueCertified, MSGBOX_DEFAULT
	releaseall
	end

DewfordTown_Gym_EventScript_GymStatue::
	msgbox DewfordTown_Gym_Text_GymStatue, MSGBOX_DEFAULT
	releaseall
	end

DewfordTown_Gym_Text_GymGuideAdvice:
	.string "Aaah ierse onzen toekomstigen\n"
	.string "Kampioen, {PLAYER}!\p"
	.string "De Panne's Gym Leidr Brawly\n"
	.string "is zot van Pokémon batteringn.\p"
	.string "In zoverre zelfs da al zin Pokémons\n"
	.string "wok van da type zin.\p"
	.string "Aje me 'normoale' Pokémons afkomt,\n"
	.string "gaje ip uw mulle krihhen,\l"
	.string "dajt ma weet!\p"
	.string "En ti nog nie gedoan...\n"
	.string "'t Is ier pekkedonker moat.\p"
	.string "Just lik de bodem van 'd oceaan...\n"
	.string "Kzinkik ne poëet é.\p"
	.string "Allez, smit u!$"

DewfordTown_Gym_Text_GymGuidePostVictory:
	.string "Whoah! It's turned too bright in here!\p"
	.string "Your future is bright, too!$"

DewfordTown_Gym_Text_TakaoIntro:
    .string "Macht en kracht!\n"
    .string "Kom mor ip!$"

DewfordTown_Gym_Text_TakaoDefeat:
    .string "Ti nie machtig genoeg…$"

DewfordTown_Gym_Text_TakaoPostBattle:
    .string "Twas machtiger dan dak krachtig was!\n"
    .string "Kmoe zeggn, goei techniek zenne!$"

DewfordTown_Gym_Text_JocelynIntro:
    .string "'N is nie jin goe reden\n"
    .string "vo Brawly om zich te moei'n!\p"
    .string "Kgoan u verpletteren!$"

DewfordTown_Gym_Text_JocelynDefeat:
    .string "Ma… allez?\n"
    .string "Hoe konnekik zo gemakkelijk verliezn?$"

DewfordTown_Gym_Text_JocelynPostBattle:
    .string "Uit uw verlies moeje leren.\n"
    .string "Da ga mij motiveren vo beter te wordn!\p"
    .string "En ton é, ip een dag, goak boaze zin\n"
	.string "van min eigen gym…\p"
    .string "Nin, beter zelfs, de Pokémon Liga\n"
    .string "Kampioen!$"

DewfordTown_Gym_Text_LauraIntro:
    .string " Ge peist toch nie da'k u ga laten doen zeker!\n"
    .string "Aje moe bleitn ist ni mijn fout eh!$"

DewfordTown_Gym_Text_LauraDefeat:
    .string "Waaaaaaah!\n"
    .string "'k Eb verloren!$"

DewfordTown_Gym_Text_LauraPostBattle:
    .string "Ik batter int donker, zo moek jun smoel ni zien!\n"
    .string "Mutten.\p"
    .string "Ma omdat zo donker es, kan’k nwoois\n"
    .string "min Pokémons deftig zien…$"

DewfordTown_Gym_Text_LilithIntro:
    .string "Ufufu…\n"
    .string "Ant tasten int donker, manneke?$"

DewfordTown_Gym_Text_LilithDefeat:
    .string "Min nederloahe…\n"
    .string "is kristal'elder, ting mie…$"

DewfordTown_Gym_Text_LilithPostBattle:
    .string "Ge verdientet om verloren te lopn en\n"
    .string "weer bie den inhang ut te komen!$"

DewfordTown_Gym_Text_BrendenIntro:
    .string "Kgoa u ne ke twôn'n wukda ne\n"
    .string "matroos ollemaal kan!$"

DewfordTown_Gym_Text_BrendenDefeat:
    .string "Mo hoe kon da nu?\n"
    .string "tegen nen Kortrijkzaan dan nog…$"

DewfordTown_Gym_Text_BrendenPostBattle:
    .string "Ey, ma! Gij zijt wel ne goeien tegenstander\n"
    .string "vo oezen Gym boaze.$"

DewfordTown_Gym_Text_CristianIntro:
    .string "Aje deure wil goan, moeje\n"
    .string "deur mie goan! Deur de meure!$"

DewfordTown_Gym_Text_CristianDefeat:
    .string "Grrrrr!\n"
    .string "Da wa deur min meure..$"

DewfordTown_Gym_Text_CristianPostBattle:
    .string "Ge wint!\n"
    .string "Pakt die medaille, jong!$"

DewfordTown_Gym_Text_BrawlyIntro:
	.string "Daag. Ik zen Brawly!\n"
	.string "Den Gym Leider van De Panne!\p"
	.string "Kben ier aanhespoeld toen dak\n"
	.string "een klin pahadderke woarn.\l"
	.string "Ip die leeftijd, ekkik zjivn doagn\n"
	.string "hespendeerd in de pekken-donkern\l"
	.string "in die hrotte ten noorden vanier.\p"
	.string "N'en echten Temmer overleeft da!\p"
	.string "En nu ist an gie, {PLAYER}!\p"
	.string "Voeldjet al aan uw woatr?\n"
	.string "Loatn we battern!$"

DewfordTown_Gym_Text_BrawlyDefeat:
	.string "Whoah, wow! Da wa nog een bitje\n"
	.string "ne splash moat! Machtig..\p"
	.string "Oké, gèt jezelve beweezn.\n"
	.string "Vangt deze Gym Medaille!$"

DewfordTown_Gym_Text_ReceivedKnuckleBadge:
	.string "{PLAYER} krigt de Vuste Medaille\n"
	.string "van den Brawly.$"

DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis:
	.string "Dankzie de Vuste Medaille, weten\n"
	.string "{PKMN} tot Level 30 daje een djoef\l"
	.string "kun utdeeln asze nie lustern.\p"
	.string "En, ge kun nu de HM Flash gebrukn\n"
	.string "butn batteringen.\p"
	.string "En omdaje hevochtn è lik n'en beir,\n"
	.string "iere, nog een TM'ke.$"

DewfordTown_Gym_Text_ExplainBulkUp:
	.string "TM08 ljirt Bulk Up an.\p"
	.string "Mjir Attak, mjir Defense..\n"
	.string "wa moe n'en Temmer nog mjir èn?p"
	.string "… … … … … …$"

DewfordTown_Gym_Text_RegisteredBrawly:
	.string "Gym Leider Brawly\n"
	.string "toehevoegd in den Pokénav.$"

DewfordTown_Gym_Text_BrawlyPostBattle:
	.string "Gie èt et talent om ip n'en dag\n"
	.string "n'en tsunami te veroorzoakn.\l"
	.string "Kzweirem!$"

DewfordTown_Gym_Text_GymStatue:
	.string "De Panne Pokémon Gym$"

DewfordTown_Gym_Text_GymStatueCertified:
	.string "De Panne Pokémon Gym\p"
	.string "Brawly's gecertificeerde Temmers:\n"
	.string "{PLAYER}$"

DewfordTown_Gym_Text_BrawlyPreRematch:
	.string "Brawly: Een holve trekt me eb terug..\n"
	.string "ma ie kom ossan were me vloed.\p"
	.string "Zukn holve lik daje gie zijt…\n"
	.string "kwist wel daje were zo' komm'n!\p"
	.string "Toon et mie!\n"
	.string "Oe hihantisch daje hewordn zyt!$"

DewfordTown_Gym_Text_BrawlyRematchDefeat:
	.string "Wow! Wukne splash were!\n"
	.string "Kzinkik hjil hedéhydrateerd jongne!$"

DewfordTown_Gym_Text_BrawlyPostRematch:
	.string "Brawly: Battrn daddis diep, zo diep.\n"
	.string "Ge kunt den bodem nie zien.\l"
	.string "Juste lik de zjêe..in 'Oen!$"

DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons:
	.string "Brawly: E' holve trekt me eb terug..\n"
	.string "ma ie kom ossan were me vloed.\p"
	.string "Zukn holve lik daje gie zijt…\n"
	.string "kwist wel daje were zo' komm'n!\p"
	.string "Oh? Mojong toch.\n"
	.string "Gebt ma jin Pokémon.\p"
	.string "Kerekewere me minstens\n"
	.string "twêe Pokémon.$"
